export const Users = [
  {
    id:1,
    profilePicture: "assets/person/1.png",
    username: "Nellis Royal",
  },
  {
    id:2,
    profilePicture: "assets/person/2.png",
    username: "Bartrian Dwigwin",
  },
  {
    id:3,
    profilePicture: "assets/person/3.png",
    username: "Alekanzro Yachet",
  },
  {
    id:4,
    profilePicture: "assets/person/4.png",
    username: "DouTali Zuzubeat",
  },
  {
    id:5,
    profilePicture: "assets/person/5.png",
    username: "Cuttor Evty",
  },
  {
    id:6,
    profilePicture: "assets/person/6.png",
    username: "McVayverter Cionson",
  },
  {
    id:7,
    profilePicture: "assets/person/7.png",
    username: "Rappliny Soder",
  },
  {
    id:8,
    profilePicture: "assets/person/8.png",
    username: "Counto Confern",
  },
  {
    id:9,
    profilePicture: "assets/person/9.png",
    username: "Bruzorn Sid",
  },
  {
    id:10,
    profilePicture: "assets/person/10.png",
    username: "Rivizin Etrom",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "I moved to this home.",
    photo: "assets/post/1.png",
    date: "7 mins ago",
    userId: 1,
    like: 170,
    comment: 55,
  },
  {
    id: 2,
    desc: "Look at this pretty old Styleish Mansion.",
    photo: "assets/post/2.png",
    date: "9 mins ago",
    userId: 2,
    like: 114,
    comment: 86,
  },
  {
    id: 3,
    desc: "1997 Styleish Stairs.",
    photo: "assets/post/3.png",
    date: "2 hour ago",
    userId: 3,
    like: 141,
    comment: 46,
  },
  {
    id: 4,
    desc: "White kitchen.",
    photo: "assets/post/4.png",
    date: "3 hours ago",
    userId: 4,
    like: 69,
    comment: 9,
  },
  {
    id: 5,
    desc: "Big Barn.",
    photo: "assets/post/5.png",
    date: "6 hours ago",
    userId: 5,
    like: 312,
    comment: 90,
  },
  {
    id: 6,
    desc: "Old Kitchen.",
    photo: "assets/post/6.png",
    date: "1 day ago",
    userId: 6,
    like: 100,
    comment: 7,
  },
  {
    id: 7,
    desc: "A hidden house thst looks small but Large.",
    photo: "assets/post/7.png",
    date: "3 days ago",
    userId: 7,
    like: 196,
    comment: 20,
  },
  {
    id: 8,
    desc: "Yellow house.",
    photo: "assets/post/8.png",
    date: "6 days ago",
    userId: 8,
    like: 90,
    comment: 4,
  },
  {
    id: 9,
    desc: "Living room hallway.",
    photo: "assets/post/9.png",
    date: "9 days ago",
    userId: 9,
    like: 287,
    comment: 54,
  },
  {
    id: 10,
    desc: "Living room with No floor open.",
    photo: "assets/post/10.png",
    date: "1 week ago",
    userId: 10,
    like: 127,
    comment: 59,
  },
];
